name: Update netease-music-box gist
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: Update gist
        uses: Leecason/netease-music-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9320dd3a2bd5ba39203cb42c69c3e23b
          USER_ID: 563282981
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
