name: Sync gist with WakaTime summary
on:
  workflow_dispatch:
  
  schedule:
    - cron: '40 1 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: superman66/wakatime-sync@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 626f23e89b0a547ac7ab81ab482c6274
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SCU_KEY: ${{ secrets.SCU_KEY }}
